[workspace]
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["conda-forge"]
name = "fire-recovery-backend"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pytest = "python -m pytest"
ruff-check = "ruff check ."
ruff-format = "ruff format ."
ruff-fix = "ruff check . --fix"

[dependencies]
numpy = ">=2.2.4,<3"
rasterio = ">=1.4.3,<2"
fastapi = ">=0.115.12,<0.116"
uvicorn = ">=0.34.2,<0.35"
coiled = ">=1.92.0,<2"
dask = ">=2025.3.0,<2026"
rio-cogeo = ">=5.4.1,<6"
pystac = ">=1.13.0,<2"
stackstac = ">=0.5.1,<0.6"
geopandas = ">=1.0.1,<2"
pixi-kernel = ">=0.6.3,<0.7"
rioxarray = ">=0.18.2,<0.19"
pystac-client = ">=0.8.6,<0.9"
pytest = ">=8.3.5,<9"
pytest-asyncio = ">=0.26.0,<0.27"
httpx = ">=0.28.1,<0.29"
jsonschema = ">=4.25.1,<5"
typing = ">=3.10.0.0,<4"
msgspec = ">=0.19.0,<0.20"
minio = ">=7.2.15,<8"
planetary-computer = ">=1.0.0,<2"
xvec = ">=0.3.1,<0.4"
exactextract = ">=0.2.2,<0.3"
fastapi-cache2 = ">=0.2.2,<0.3"
mypy = ">=1.16.0,<2"
pytest-dotenv = ">=0.5.2,<0.6"
obstore = ">=0.7.3,<0.8"
stac-check = ">=1.3.3,<2"
ruff = ">=0.12.9,<0.13"
geojson-pydantic = ">=2.0.0,<3"

[pypi-dependencies]
stac-pydantic = ">=3.2.0, <4"
